name = "Manual_BlockTales_WolfBoi008"
display_name = "Manual: Block Tales"
home = "https://github.com/WolfBoi008/Block-Tales"
default_url = "https://github.com/WolfBoi008/Block-Tales/releases/download/{{version}}/manual_blocktales_wolfboi008.apworld"

[versions]
"4.1.0" = {}
