name = "Manual_TooManyNights_WolfBoi008"
display_name = "Manual: Too Many Nights"
home = "https://github.com/WolfBoi008/Too-Many-Nights"

[versions]
"2.1.0+a" = { url = "https://github.com/WolfBoi008/Too-Many-Nights/releases/tag/2.1.0a" }
